#!/usr/bin/env python3
"""Patch comments-panel.js to add context menu and poster generation."""
import sys

FILE = r'C:\Users\kiomosu\Desktop\kimoPlayer\src\features\comments-panel.js'

with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

target = '// \u2550\u2550 \u6a21\u5757\u7ea7\u5f15\u7528 \u2550\u2550'
idx = content.find(target)
if idx == -1:
    print('ERROR: target not found')
    sys.exit(1)

print(f'Found target at index {idx}')

# Build the new code as a list of lines to avoid encoding issues
lines = []
lines.append('// \u2550\u2550 \u8bc4\u8bba\u53f3\u952e\u83dc\u5355 \u2550\u2550')
lines.append('let contextMenuEl = null;')
lines.append('let contextMenuComment = null;')
lines.append('')
lines.append('function ensureContextMenu() {')
lines.append('  if (contextMenuEl) return contextMenuEl;')
lines.append("  contextMenuEl = document.createElement('div');")
lines.append("  contextMenuEl.className = 'comment-context-menu';")
lines.append('  contextMenuEl.innerHTML = `')
lines.append('    <div class="comment-context-menu-item" data-action="poster">')
lines.append('      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>')
lines.append('      \u751f\u6210\u8bc4\u8bba\u6d77\u62a5')
lines.append('    </div>')
lines.append('    <div class="comment-context-menu-divider"></div>')
lines.append('    <div class="comment-context-menu-item" data-action="copy">')
lines.append('      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>')
lines.append('      \u590d\u5236\u8bc4\u8bba\u5185\u5bb9')
lines.append('    </div>')
lines.append('  `;')
lines.append("  document.body.appendChild(contextMenuEl);")
lines.append('')
lines.append("  contextMenuEl.addEventListener('click', (e) => {")
lines.append("    const item = e.target.closest('.comment-context-menu-item');")
lines.append('    if (!item) return;')
lines.append('    const action = item.dataset.action;')
lines.append('    hideContextMenu();')
lines.append("    if (action === 'poster' && contextMenuComment) {")
lines.append('      generateCommentPoster(contextMenuComment);')
lines.append("    } else if (action === 'copy' && contextMenuComment) {")
lines.append("      const text = contextMenuComment.content || '';")
lines.append("      navigator.clipboard.writeText(text).then(() => showToast('\u8bc4\u8bba\u5185\u5bb9\u5df2\u590d\u5236'));")
lines.append('    }')
lines.append('  });')
lines.append('')
lines.append("  document.addEventListener('mousedown', (e) => {")
lines.append('    if (contextMenuEl && !contextMenuEl.contains(e.target)) {')
lines.append('      hideContextMenu();')
lines.append('    }')
lines.append('  });')
lines.append('')
lines.append('  return contextMenuEl;')
lines.append('}')
lines.append('')
lines.append('function showContextMenu(x, y, commentData) {')
lines.append('  const menu = ensureContextMenu();')
lines.append('  contextMenuComment = commentData;')
lines.append("  menu.style.left = '0';")
lines.append("  menu.style.top = '0';")
lines.append("  menu.style.display = 'block';")
lines.append('  const rect = menu.getBoundingClientRect();')
lines.append('  const maxX = window.innerWidth - rect.width - 8;')
lines.append('  const maxY = window.innerHeight - rect.height - 8;')
lines.append("  menu.style.left = Math.min(x, maxX) + 'px';")
lines.append("  menu.style.top = Math.min(y, maxY) + 'px';")
lines.append('}')
lines.append('')
lines.append('function hideContextMenu() {')
lines.append('  if (contextMenuEl) {')
lines.append("    contextMenuEl.style.display = 'none';")
lines.append('    contextMenuComment = null;')
lines.append('  }')
lines.append('}')
lines.append('')
lines.append('// \u2550\u2550 \u8bc4\u8bba\u6d77\u62a5\u751f\u6210 \u2550\u2550')
lines.append('')
lines.append('function wrapText(ctx, text, maxWidth) {')
lines.append('  const lines = [];')
lines.append("  let currentLine = '';")
lines.append('  for (const char of text) {')
lines.append("    if (char === '\\n') {")
lines.append('      lines.push(currentLine);')
lines.append("      currentLine = '';")
lines.append('      continue;')
lines.append('    }')
lines.append('    const testLine = currentLine + char;')
lines.append('    if (ctx.measureText(testLine).width > maxWidth) {')
lines.append('      lines.push(currentLine);')
lines.append('      currentLine = char;')
lines.append('    } else {')
lines.append('      currentLine = testLine;')
lines.append('    }')
lines.append('  }')
lines.append('  if (currentLine) lines.push(currentLine);')
lines.append('  return lines;')
lines.append('}')
lines.append('')
lines.append('async function generateCommentPoster(comment) {')
lines.append('  const canvas = document.createElement("canvas");')
lines.append('  canvas.width = 540;')
lines.append('  const ctx = canvas.getContext("2d");')
lines.append('')
lines.append('  try {')
lines.append('    await document.fonts.load(\'bold 28px "Microsoft YaHei"\');')
lines.append('    await document.fonts.load(\'20px "Microsoft YaHei"\');')
lines.append('    await document.fonts.load(\'16px "Microsoft YaHei"\');')
lines.append('    await document.fonts.load(\'14px "Microsoft YaHei"\');')
lines.append('  } catch (e) {}')
lines.append('')
lines.append('  const user = comment.user || {};')
lines.append("  const nickname = user.nickname || '\u533f\u540d\u7528\u6237';")
lines.append('  const avatarUrl = user.avatarUrl;')
lines.append('  const content = comment.content || "";')
lines.append('  const platform = comment.platform;')
lines.append('  const platformInfo = getPlatformInfo(platform);')
lines.append('  const likedCount = comment.likedCount || 0;')
lines.append('  const time = formatTime(comment.time);')
lines.append('')
lines.append('  // \u7ed8\u5236\u80cc\u666f')
lines.append('  const gradient = ctx.createLinearGradient(0, 0, 540, 540);')
lines.append("  gradient.addColorStop(0, '#1a1a2e');")
lines.append("  gradient.addColorStop(0.5, '#16213e');")
lines.append("  gradient.addColorStop(1, '#0f3460');")
lines.append('  ctx.fillStyle = gradient;')
lines.append('  ctx.fillRect(0, 0, 540, 540);')
lines.append('')
lines.append('  // \u88c5\u9970\u5706')
lines.append('  ctx.globalAlpha = 0.06;')
lines.append("  ctx.fillStyle = '#fff';")
lines.append('  ctx.beginPath();')
lines.append('  ctx.arc(480, 60, 120, 0, Math.PI * 2);')
lines.append('  ctx.fill();')
lines.append('  ctx.beginPath();')
lines.append('  ctx.arc(60, 480, 80, 0, Math.PI * 2);')
lines.append('  ctx.fill();')
lines.append('  ctx.globalAlpha = 1;')
lines.append('')
lines.append('  let y = 40;')
lines.append('')
lines.append('  // \u6b4c\u66f2\u4fe1\u606f')
lines.append("  ctx.fillStyle = 'rgba(255,255,255,0.5)';")
lines.append('  ctx.font = \'14px "Microsoft YaHei"\';')
lines.append("  ctx.fillText('\\ud83c\\udfb5 ' + currentTitle + ' - ' + currentArtist, 40, y);")
lines.append('  y += 36;')
lines.append('')
lines.append('  // \u5206\u9694\u7ebf')
lines.append("  ctx.strokeStyle = 'rgba(255,255,255,0.1)';")
lines.append('  ctx.lineWidth = 1;')
lines.append('  ctx.beginPath();')
lines.append('  ctx.moveTo(40, y);')
lines.append('  ctx.lineTo(500, y);')
lines.append('  ctx.stroke();')
lines.append('  y += 24;')
lines.append('')
lines.append('  // \u8bc4\u8bba\u5185\u5bb9')
lines.append("  ctx.fillStyle = 'rgba(255,255,255,0.92)';")
lines.append('  ctx.font = \'20px "Microsoft YaHei"\';')
lines.append('  const contentLines = wrapText(ctx, content, 440);')
lines.append('  for (const line of contentLines) {')
lines.append('    ctx.fillText(line, 40, y);')
lines.append('    y += 30;')
lines.append('  }')
lines.append('  y += 20;')
lines.append('')
lines.append('  // \u5206\u9694\u7ebf')
lines.append('  ctx.beginPath();')
lines.append('  ctx.moveTo(40, y);')
lines.append('  ctx.lineTo(500, y);')
lines.append('  ctx.stroke();')
lines.append('  y += 28;')
lines.append('')
lines.append('  // \u7528\u6237\u5934\u50cf')
lines.append('  if (avatarUrl) {')
lines.append('    try {')
lines.append('      const avatarImg = new Image();')
lines.append("      avatarImg.crossOrigin = 'anonymous';")
lines.append('      await new Promise((resolve, reject) => {')
lines.append('        avatarImg.onload = resolve;')
lines.append('        avatarImg.onerror = reject;')
lines.append('        avatarImg.src = avatarUrl;')
lines.append('      });')
lines.append('      ctx.save();')
lines.append('      ctx.beginPath();')
lines.append('      ctx.arc(60, y + 18, 18, 0, Math.PI * 2);')
lines.append('      ctx.clip();')
lines.append('      ctx.drawImage(avatarImg, 42, y, 36, 36);')
lines.append('      ctx.restore();')
lines.append('    } catch (e) {')
lines.append("      ctx.fillStyle = 'rgba(255,255,255,0.2)';")
lines.append('      ctx.beginPath();')
lines.append('      ctx.arc(60, y + 18, 18, 0, Math.PI * 2);')
lines.append('      ctx.fill();')
lines.append('    }')
lines.append('  }')
lines.append('')
lines.append("  ctx.fillStyle = 'rgba(255,255,255,0.85)';")
lines.append('  ctx.font = \'bold 16px "Microsoft YaHei"\';')
lines.append('  ctx.fillText(nickname, 88, y + 16);')
lines.append('')
lines.append('  if (platformInfo) {')
lines.append("    ctx.fillStyle = 'rgba(255,255,255,0.4)';")
lines.append('    ctx.font = \'13px "Microsoft YaHei"\';')
lines.append("    ctx.fillText(platformInfo.icon + ' ' + platformInfo.name, 88, y + 36);")
lines.append('  }')
lines.append('')
lines.append('  // \u70b9\u8d5e\u6570')
lines.append('  if (likedCount > 0) {')
lines.append("    ctx.fillStyle = 'rgba(255,255,255,0.5)';")
lines.append('    ctx.font = \'14px "Microsoft YaHei"\';')
lines.append("    ctx.textAlign = 'right';")
lines.append("    ctx.fillText('\\u2764\\ufe0f ' + likedCount, 500, y + 16);")
lines.append("    ctx.textAlign = 'left';")
lines.append('  }')
lines.append('')
lines.append('  // \u65f6\u95f4')
lines.append('  if (time) {')
lines.append("    ctx.fillStyle = 'rgba(255,255,255,0.3)';")
lines.append('    ctx.font = \'12px "Microsoft YaHei"\';')
lines.append("    ctx.textAlign = 'right';")
lines.append('    ctx.fillText(time, 500, y + 36);')
lines.append("    ctx.textAlign = 'left';")
lines.append('  }')
lines.append('')
lines.append('  y += 60;')
lines.append('')
lines.append('  // \u5e95\u90e8\u54c1\u724c')
lines.append("  ctx.fillStyle = 'rgba(255,255,255,0.2)';")
lines.append('  ctx.font = \'12px "Microsoft YaHei"\';')
lines.append("  ctx.textAlign = 'center';")
lines.append("  ctx.fillText('KimiPlayer \\u00b7 \\u8bc4\\u8bba\\u5206\\u4eab', 270, 520);")
lines.append("  ctx.textAlign = 'left';")
lines.append('')
lines.append('  showPosterPreview(canvas);')
lines.append('}')
lines.append('')
lines.append('function showPosterPreview(canvas) {')
lines.append("  const dataUrl = canvas.toDataURL('image/png');")
lines.append('')
lines.append("  const overlay = document.createElement('div');")
lines.append("  overlay.className = 'poster-preview-overlay';")
lines.append('  overlay.innerHTML = `')
lines.append('    <div class="poster-preview-modal">')
lines.append('      <div class="poster-preview-title">\u8bc4\u8bba\u6d77\u62a5\u9884\u89c8</div>')
lines.append('      <div class="poster-preview-image-wrap">')
lines.append('        <img src="${dataUrl}" alt="\u8bc4\u8bba\u6d77\u62a5" />')
lines.append('      </div>')
lines.append('      <div class="poster-preview-actions">')
lines.append('        <button class="poster-btn-copy">\ud83d\udccb \u590d\u5236\u56fe\u7247</button>')
lines.append('        <button class="poster-btn-save">\ud83d\udcbe \u4fdd\u5b58\u5230\u672c\u5730</button>')
lines.append('        <button class="poster-btn-close">\u2715 \u5173\u95ed</button>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  `;')
lines.append("  document.body.appendChild(overlay);")
lines.append('')
lines.append("  overlay.addEventListener('click', (e) => {")
lines.append('    if (e.target === overlay) overlay.remove();')
lines.append('  });')
lines.append('')
lines.append("  overlay.querySelector('.poster-btn-copy').addEventListener('click', async () => {")
lines.append('    try {')
lines.append("      const blob = await new Promise(r => canvas.toBlob(r, 'image/png'));")
lines.append('      await navigator.clipboard.write([')
lines.append("        new ClipboardItem({ 'image/png': blob })")
lines.append('      ]);')
lines.append("      showToast('\u6d77\u62a5\u5df2\u590d\u5236\u5230\u526a\u8d34\u677f');")
lines.append('      overlay.remove();')
lines.append('    } catch (e) {')
lines.append("      showToast('\u590d\u5236\u5931\u8d25: ' + e.message);")
lines.append('    }')
lines.append('  });')
lines.append('')
lines.append("  overlay.querySelector('.poster-btn-save').addEventListener('click', async () => {")
lines.append('    try {')
lines.append("      const blob = await new Promise(r => canvas.toBlob(r, 'image/png'));")
lines.append('      const arrayBuffer = await blob.arrayBuffer();')
lines.append('      const uint8Array = new Uint8Array(arrayBuffer);')
lines.append("      const filePath = await invoke('save_file_dialog', {")
lines.append("        defaultPath: '\u8bc4\u8bba\u6d77\u62a5_' + currentTitle + '_' + Date.now() + '.png',")
lines.append("        filters: [{ name: 'PNG', extensions: ['png'] }]")
lines.append('      });')
lines.append('      if (filePath) {')
lines.append("        await invoke('write_binary_file', { path: filePath, data: Array.from(uint8Array) });")
lines.append("        showToast('\u6d77\u62a5\u5df2\u4fdd\u5b58');")
lines.append('        overlay.remove();')
lines.append('      }')
lines.append('    } catch (e) {')
lines.append("      showToast('\u4fdd\u5b58\u5931\u8d25: ' + e.message);")
lines.append('    }')
lines.append('  });')
lines.append('')
lines.append("  overlay.querySelector('.poster-btn-close').addEventListener('click', () => overlay.remove());")
lines.append('}')
lines.append('')
lines.append('function formatTime(timestamp) {')
lines.append("  if (!timestamp) return '';")
lines.append("  const date = new Date(typeof timestamp === 'number' && timestamp < 1e12 ? timestamp * 1000 : timestamp);")
lines.append('  const now = new Date();')
lines.append('  const diff = now - date;')
lines.append("  if (diff < 60000) return '\u521a\u521a';")
lines.append("  if (diff < 3600000) return Math.floor(diff / 60000) + '\u5206\u949f\u524d';")
lines.append("  if (diff < 86400000) return Math.floor(diff / 3600000) + '\u5c0f\u65f6\u524d';")
lines.append("  if (diff < 2592000000) return Math.floor(diff / 86400000) + '\u5929\u524d';")
lines.append("  return date.getFullYear() + '-' + String(date.getMonth()+1).padStart(2,'0') + '-' + String(date.getDate()).padStart(2,'0');")
lines.append('}')
lines.append('')

new_code = '\n'.join(lines)

content = content[:idx] + new_code + content[idx:]

with open(FILE, 'w', encoding='utf-8') as f:
    f.write(content)

print('OK: context menu + poster code inserted')
